#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Generated bytes only: current metadata/sampled identity and symlink freshness."""
import argparse,hashlib,json,os,tempfile
from pathlib import Path
import subprocess
ROOT=Path(__file__).resolve().parents[2]
ap=argparse.ArgumentParser();ap.add_argument('--helper',type=Path,default=ROOT/'work/build/thumbnail-helper/thumbnail-helper');ap.add_argument('--output',type=Path,required=True);a=ap.parse_args()
a.helper=a.helper.resolve();a.output=a.output.resolve()
if not a.output.is_relative_to(ROOT/'work/validation/story004') or a.output.exists():ap.error('Fresh owned output required')
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
checks=[]
def identity(path,policy):
 r=subprocess.run([str(a.helper),'--fingerprint',policy,'--input',str(path)],capture_output=True,timeout=20)
 assert r.returncode==0,(r.returncode,r.stderr)
 v=json.loads(r.stdout);assert v['ok'] and v['policy']==policy;return v
with tempfile.TemporaryDirectory(prefix='source-identity-',dir=ROOT/'work/validation/story004') as folder:
 root=Path(folder);first=root/'first.bin';second=root/'second.bin';link=root/'source.bin'
 first.write_bytes(b'a'*(8*1024*1024));second.write_bytes(b'b'*(8*1024*1024));link.symlink_to(first)
 before=identity(first,'stat');sampled=identity(first,'sampled');unchanged=identity(first,'sampled')
 assert before['stat_identity']==sampled['stat_identity']==unchanged['stat_identity'] and sampled['fingerprint']==unchanged['fingerprint'];checks.append('unchanged metadata and sampled fingerprint repeat deterministically')
 saved=first.stat();
 with first.open('r+b') as f:f.write(b'c')
 os.utime(first,ns=(saved.st_atime_ns,saved.st_mtime_ns));modified=identity(first,'sampled')
 assert first.stat().st_size==saved.st_size and first.stat().st_mtime_ns==saved.st_mtime_ns
 assert modified['stat_identity']!=sampled['stat_identity'] and modified['fingerprint']!=sampled['fingerprint'];checks.append('same-size preserved-mtime sampled edit changes identity and content fingerprint')
 before_link=identity(link,'sampled');link.unlink();link.symlink_to(second);after_link=identity(link,'sampled')
 assert before_link['stat_identity']!=after_link['stat_identity'] and before_link['fingerprint']!=after_link['fingerprint'];checks.append('same URI symlink retarget follows new object and rejects old identity')
 # Atomic replacement with equal bytes/length/mtime still changes object identity.
 replacement=root/'replacement.bin';replacement.write_bytes(first.read_bytes());os.utime(replacement,ns=(saved.st_atime_ns,saved.st_mtime_ns));prior=identity(first,'stat');os.replace(replacement,first);replaced=identity(first,'stat')
 assert prior['stat_identity']!=replaced['stat_identity'];checks.append('equal-content equal-size preserved-mtime atomic replacement changes identity')
result={'passed':True,'scope':'Generated-file metadata/sampled freshness, no native UI or durable label identity proof','helper_sha256':digest(a.helper),'source_sha256':digest(ROOT/'src/thumbnail-helper/thumbnail-helper.c'),'checks':checks}
a.output.write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result))
