#!/usr/bin/env bash
set -euo pipefail

MODE="apply"
case "${1:-}" in
  "")
    ;;
  "--check")
    MODE="check"
    ;;
  "--sync-aliases")
    MODE="sync_aliases"
    ;;
  "--check-aliases")
    MODE="check_aliases"
    ;;
  *)
    echo "Usage: sync-agent-skills.sh [--check|--sync-aliases|--check-aliases]" >&2
    exit 2
    ;;
esac

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CANONICAL="$ROOT/.agents/skills"
LEGACY="$ROOT/skills"
CLAUDE_LINK="$ROOT/.claude/skills"
CURSOR_LINK="$ROOT/.cursor/skills"
GEMINI_COMMANDS_DIR="$ROOT/.gemini/commands"

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

ensure_symlink() {
  local link_path="$1"
  local target_rel="$2"

  if [[ "$MODE" == "check" ]]; then
    [[ -L "$link_path" ]] || fail "$link_path is not a symlink"
    local actual
    actual="$(readlink "$link_path")"
    [[ "$actual" == "$target_rel" ]] || fail "$link_path points to '$actual' (expected '$target_rel')"
    return
  fi

  if [[ -e "$link_path" && ! -L "$link_path" ]]; then
    fail "Refusing to overwrite non-symlink $link_path. Migrate manually first."
  fi
  mkdir -p "$(dirname "$link_path")"
  rm -f "$link_path"
  ln -s "$target_rel" "$link_path"
}

parse_frontmatter_field() {
  local skill_file="$1"
  local field="$2"
  awk -v field="$field" '
    BEGIN { in_fm=0; fm_seen=0 }
    /^---[[:space:]]*$/ {
      if (fm_seen == 0) { in_fm=1; fm_seen=1; next }
      if (in_fm == 1) { in_fm=0; next }
    }
    in_fm == 1 {
      pat = "^" field ":[[:space:]]*"
      if ($0 ~ pat) {
        sub(pat, "", $0)
        gsub(/^"|"$/, "", $0)
        print $0
        exit
      }
    }
  ' "$skill_file"
}

render_alias() {
  local skill_name="$1"
  local desc="$2"
  cat <<TOML
# Generated by scripts/sync-agent-skills.sh. Do not edit manually.
description = "$desc"
prompt = """
Use the canonical project skill at .agents/skills/$skill_name/SKILL.md.

Follow that skill exactly, then execute the requested task.
If the user passed command arguments, incorporate them here: {{args}}
"""
TOML
}

validate_canonical_skills() {
  local skill_count=0
  while IFS= read -r skill_file; do
    [[ -n "$skill_file" ]] || continue
    invocable="$(parse_frontmatter_field "$skill_file" "user-invocable")"
    [[ -n "$invocable" ]] || fail "$skill_file is missing required frontmatter field: user-invocable"
    desc="$(parse_frontmatter_field "$skill_file" "description")"
    [[ -n "$desc" ]] || fail "$skill_file is missing required frontmatter field: description"
    skill_count=$((skill_count + 1))
  done < <(find "$CANONICAL" -mindepth 2 -maxdepth 2 -name SKILL.md | LC_ALL=C sort)

  [[ "$skill_count" -gt 0 ]] || fail "No canonical skills found in $CANONICAL"
  echo "$skill_count"
}

sync_aliases() {
  mkdir -p "$GEMINI_COMMANDS_DIR"
  rm -f "$GEMINI_COMMANDS_DIR"/*.toml

  local alias_count=0
  while IFS= read -r skill_file; do
    [[ -n "$skill_file" ]] || continue
    skill_dir="$(dirname "$skill_file")"
    skill_name="$(basename "$skill_dir")"
    invocable="$(parse_frontmatter_field "$skill_file" "user-invocable")"
    [[ "$invocable" == "false" ]] && continue
    desc="$(parse_frontmatter_field "$skill_file" "description")"
    printf '%s\n' "$(render_alias "$skill_name" "$desc")" > "$GEMINI_COMMANDS_DIR/$skill_name.toml"
    alias_count=$((alias_count + 1))
  done < <(find "$CANONICAL" -mindepth 2 -maxdepth 2 -name SKILL.md | LC_ALL=C sort)

  echo "$alias_count"
}

check_aliases() {
  local alias_count=0
  while IFS= read -r skill_file; do
    [[ -n "$skill_file" ]] || continue
    skill_dir="$(dirname "$skill_file")"
    skill_name="$(basename "$skill_dir")"
    invocable="$(parse_frontmatter_field "$skill_file" "user-invocable")"
    [[ "$invocable" == "false" ]] && continue
    desc="$(parse_frontmatter_field "$skill_file" "description")"
    out_file="$GEMINI_COMMANDS_DIR/$skill_name.toml"
    expected_alias="$(render_alias "$skill_name" "$desc")"
    [[ -f "$out_file" ]] || fail "Missing command alias: $out_file"
    actual_alias="$(cat "$out_file")"
    [[ "$actual_alias" == "$expected_alias" ]] || fail "Command alias content drifted: $out_file"
    alias_count=$((alias_count + 1))
  done < <(find "$CANONICAL" -mindepth 2 -maxdepth 2 -name SKILL.md | LC_ALL=C sort)

  local file_count
  if [[ -d "$GEMINI_COMMANDS_DIR" ]]; then
    file_count="$(find "$GEMINI_COMMANDS_DIR" -maxdepth 1 -name '*.toml' | wc -l | tr -d ' ')"
  else
    file_count="0"
  fi
  [[ "$file_count" -eq "$alias_count" ]] || fail "Command alias count ($file_count) != invocable skills ($alias_count)"
  echo "$alias_count"
}

[[ -d "$CANONICAL" ]] || fail "Canonical skills dir missing: $CANONICAL"

if [[ "$MODE" == "check" ]]; then
  [[ -L "$LEGACY" ]] || fail "$LEGACY is not a symlink"
  [[ "$(readlink "$LEGACY")" == ".agents/skills" ]] || fail "$LEGACY should point to .agents/skills"
else
  if [[ "$MODE" == "apply" && -d "$LEGACY" && ! -L "$LEGACY" ]]; then
    fail "Refusing to overwrite non-symlink $LEGACY. Migrate manually first."
  fi
  if [[ "$MODE" == "apply" ]]; then
    rm -f "$LEGACY"
    ln -s .agents/skills "$LEGACY"
  fi
fi

if [[ "$MODE" == "sync_aliases" ]]; then
  alias_count="$(sync_aliases)"
  echo "alias-sync: OK ($alias_count command aliases)"
  exit 0
fi

if [[ "$MODE" == "check_aliases" ]]; then
  alias_count="$(check_aliases)"
  echo "alias-check: OK ($alias_count command aliases)"
  exit 0
fi

ensure_symlink "$CLAUDE_LINK" "../.agents/skills"
ensure_symlink "$CURSOR_LINK" "../.agents/skills"
skill_count="$(validate_canonical_skills)"
echo "skills-check: OK ($skill_count canonical skills; compatibility links ok; command aliases optional)"
